# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: default 

variables:
  resource_group_name: 'cc'
  storage_account_name: 'inf20068ccstorage'
  container_name: 'tfstate-db'
  file_key: 'terraform.tfstate'
  environmentServiceNameAzureRM: "Azure-cc-Connection"

stages:

  - stage: tfdestroy
    jobs:
      - job: destroy
        steps:
          - task: TerraformInstaller@1
            displayName: Terraform install
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            displayName: 'init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Azure-cc-Connection'
              backendAzureRmResourceGroupName: '$(resource_group_name)'
              backendAzureRmStorageAccountName: '$(storage_account_name)'
              backendAzureRmContainerName: '$(container_name)'
              backendAzureRmKey: '$(file_key)'
              workingDirectory: '$(System.DefaultWorkingDirectory)/database'

          - task: DownloadSecureFile@1
            inputs:
              secureFile: 'temp'
            continueOnError: false
            
          - task: TerraformTaskV4@4
            displayName: 'destroy'
            inputs:
              environmentServiceNameAzureRM: 'Azure-cc-Connection'
              provider: 'azurerm'
              command: 'destroy'
              workingDirectory: '$(System.DefaultWorkingDirectory)/database'
